### ISSUE TITLE
Better errors when a deployer or pragma doesn't report it's authoring meta hash

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/rain.orderbook#644]
## Problem
In our app, there's now a "words" tab, that when successfull will show the words for all deployers and pragmas in the order.

![Image](https://github.com/rainlanguage/rain.orderbook/assets/1190022/c9c0e28d-83f2-4c42-9482-22d67bd5ef8d)

This generally works ok, but we have unhelpful errors when the deployer or pragma doesn't have the IDescribedByMetaV1 interface.

### Case 1:
If the deployer is a real deployer but one that doesn't have the `describedByMetaV1` method, we get:

<img width="896" alt="image" src="https://github.com/rainlanguage/rain.orderbook/assets/1190022/bea12b0b-13da-45e3-9ba3-6ebe04c6362f">

To reproduce this use:

```
  flare:
    address: 0x550878091b2B1506069F61ae59e3A5484Bca9166
    network: flare
```

### Case 2:
The other error occurs if the deployer address is just totally wrong:
![Image](https://github.com/rainlanguage/rain.orderbook/assets/1190022/5f406fed-1095-4e7e-b28d-5a6345c286b8)

To reproduce this use:

```
  flare:
    address: 0x550878091c2B1506069F61ae59e3A5484Bca9166
    network: flare
```

## Potential solution

The unhelpful error is coming from here:

https://github.com/rainlanguage/rain.metadata/blob/2024-05-06-metaboard-errors/crates/cli/src/meta/types/authoring/v2.rs#L134

The correct appraoch is to use ERC165 to check for the IDescribedByMetaV1 interface and return a specific error if it's not found - "Contract has no words".

Will require two PRs, one for [rain.metadata](https://github.com/rainlanguage/rain.metadata) with the chagne and one for [rain.orderbook](https://github.com/rainlanguage/rain.orderbook) with a bump to the `lib/rain.metadata` crate.

todo:
- [x] - changes required in interpreter repo: https://github.com/rainlanguage/rain.interpreter/pull/234
- [x] - changes required in typecast repo: https://github.com/rainlanguage/alloy-ethers-typecast/pull/29
- [x] - setup erc repo: https://github.com/rainlanguage/rain.erc/
- [x] - changes required in metadata repo: https://github.com/rainlanguage/rain.metadata/pull/42
- [x] - update interpreter repo deps: https://github.com/rainlanguage/rain.interpreter/pull/253
- [x] - changes required in ob repo: #688
