### ISSUE TITLE
Quote orders

### ISSUE THREAD

**Issue by hardyjosh** [rainlanguage/rain.orderbook#709]
At the moment we can eval rainlang on a fork, functionality provided by the crates in https://github.com/rainlanguage/rain.interpreter

For live orders, this doesn't work so easily because orderbook inserts its own context, and has its own namespace for the store.

I believe @thedavidmeister is planning on adding a `quote` fn to `IOrderbookV4`, after that we'll need a Rust interface where, for example, we can provide a subgraph endpoint, rpc url, orderbook address and a subgraph hash and the order will be quoted.

Some of the features we'd need for this crate:
- quote any order
- quote on a fork
- persist fork caches to allow for quoting multiple orders with one fork
- quote on a historical block

---

## todo:
this is set in a workspace crate called `quote`, with reason to have it standalone and as light as possible and not necessarily paired with other non related functionalities in common crate and having it as standalone light CLI bin that can be consumed easily by bot, the CLI then can be easily added to the main orderbook CLI.

The PRs are as follows in order (all PRs are chained after each other in order):

- [x] - base quote on fork functionalities: #720 (rejected in favor of normal rpc eth_call using multicall3) 
- [x] - base quote functionalities on rpc: #722 
- [x] - update subgraph crate with a query for batch order query: #723 
- [x] - main functionalities that can read from sg and quote or quote directly given order id and orderbook address: #724
- [x] - CLI code logic for quoting: #728 
- [ ] - Update quote subgraph query to multiob sg schema

**Comment by hardyjosh** [comment]
There's a wip PR up now for a basic quote

https://github.com/rainlanguage/rain.orderbook/pull/711

**Comment by hardyjosh** [comment]
To close this issue:
- a new struct in `rain_orderbook_common` called `OrderQuoter`
- this should use `Forker` under the hood in the same way that `FuzzRunner` does
- will need to take a sg, rpc on construction
- `quote` fn so we can quote some orderhash for some orderbook address
- `quote_many` that takes a vec of orderbooks with a vec of order hashes

**Comment by rouzwelt** [comment]
this is set in a workspace crate called `quote`, with reason to have it standalone and as light as possible and not necessarily paired with other non related functionalities in common crate, the PRs are as follows in order:

- [x] - base quote on fork functionalities: #720 
- [x] - base quote functionalities on rpc: #722 
- [x] - update subgraph crate with a query for batch order query: #723 
- [x] - main functionalities that can read from sg and quote or quote directly given order id and orderbook address: #724
- [ ] - CLI code logic for quoting
