### ISSUE TITLE
Filling in gas fee values

### ISSUE THREAD

**Issue by mattyg** [rainlanguage/rain.orderbook#79]
Rather than expecting users to figure out the fees necessary to get their transactions validated in a reasonable timeframe, we should:
- Use a 3rd party api to determine the max_priority_fee_per_gas required for a slower, average, or faster transaction validation
- default to "average" priority fee
- In CLI:  add argument for transaction commands: `--priority-fee-speed` "slow", "average", "fast"
- In GUI: allow user to override priority-fee-speed for all transactions in a Settings page.

**todo**
- [ ] determine api for flare network gas estimation
- [ ] implement wrapper for gas estimation apis, potentially using ethers-rs gas oracle middleware
- [ ] modify cli to use gas estimation
- [ ] modify gui to use gas estimation

**Comment by mattyg** [comment]
Just want to confirm this makes sense to you @thedavidmeister @hardyjosh - or if you have another suggestion.

**Comment by hardyjosh** [comment]
@mattyg there's a gas oracle middleware for ethers - can we use that?

https://www.gakonst.com/ethers-rs/middleware/gas-oracle.html

**Comment by mattyg** [comment]
> @mattyg there's a gas oracle middleware for ethers - can we use that?
> 
> https://www.gakonst.com/ethers-rs/middleware/gas-oracle.html

So the ethers gas oracle middleware just offers wrappers for a several different 3rd party apis. It looks like the only wrapper that implemented support for eip1559 estimation is blocknative. But unfortunately Blocknative only supports ethereum and polygon mainnets.

What chains do you need to support in the short term? And which do you aim to support longer-term? We may want to do some research into alternative 3rd party apis, choose one based on its pricing and chains support, and then implement the ethers gas oracle middleware for it ourselves. 

Another (more complex) option for an chain-agnostic gas estimation could be to make an `eth_feeHistory` rpc call and then calculate our own slow, average, fast fees for the prior block -- that would work fine when demand is relatively stable from one block to the next.

**Comment by mattyg** [comment]
Flare's dev support did not know of any gas estimation api supporting the network:
![image](https://github.com/rainlanguage/rain.orderbook/assets/159270/b754ec45-ea9e-43cb-ae6a-b7a832717d6b)

**Comment by mattyg** [comment]
Resolved by #167
